### PR TITLE
Find by address

### LINKED ISSUE #139: Find by address
`find a/KEYWORD` finds by address

This is a feature flaw because this might be unexpected behaviour for the user, where the default behaviour is `find KEYWORD` and the keyword is just the name, but we currently have other `find` formats such as `find s/` and `find r/`. This issue is to make the find command more intuitive and consistent throughout the app.

### PR DESCRIPTION
**Pull request by keiran0**
Closes #139 

This PR allows users to enter find a/KEYWORD. What is returned is any person that has an address containing KEYWORD (i.e. allows partial match).

Also contains testcases for the new predicate.

### CODE REVIEW

File: src/main/java/seedu/tutor/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -50,6 +51,20 @@ public FindCommand parse(String args) throws ParseException {
             return new FindCommand(new SubjectContainsStringPredicate(trimmed));
         }
 
+        if (trimmedArgs.startsWith("a/")) {
+
+            String trimmed = trimmedArgs.substring(2).trim();
+            String slashRegex = "[ /]+$";
+            if (trimmed.isEmpty() || trimmed.matches(slashRegex)) {
```
Comment (LinqWithQ) [inline src/main/java/seedu/tutor/logic/parser/FindCommandParser.java]: this doesn't catch "find a/a/a" and "find a/a a", both are accepted.
